### ISSUE TITLE
Process blocks when trying to search with no internet

### ISSUE THREAD

**Issue by xave** [lazamar/haskell-docs-cli#11]
Currently, if you try to search for something when offline, the app hangs. 

Current behavior:
<no internet>

```
$ hdc
$ fromString
fetching: https://hoogle.haskell.org/?mode=json&start=1&hoogle=fromString
```
<Hangs forever. Not responsive to `CTRL+C`.>

Desired behavior:
1. Check network connection
2. On no connection send message such as:
`"You are not connected to a network. Please consider running a local hoogle instance"`

**Comment by lazamar** [comment]
Thanks for the report.
I was experiencing something similar in August. I think Hoogle was having some performance issues and taking very long to respond. You probably were experiencing the same.

This means you weren't truly offline. When one is totally offline you do get a message to check your connection
```
> map
fetching: https://hoogle.haskell.org/?mode=json&start=1&hoogle=map
Failed: *** HTTP Error: connection failure. Check your internet connection
```

I couldn't reproduce the failure to respond to `CTRL+C` behaviour. Looking at the code I can't see any place where it could be swallowing the async exception.

**Comment by xave** [comment]
Thanks for looking into this. It makes sense to me.
