### ISSUE TITLE
Github release?

### ISSUE THREAD

**Issue by unhammer** [lazamar/haskell-docs-cli#12]
I see actions are already set up and artifacts are uploaded – https://github.com/lazamar/haskell-docs-cli/actions/runs/11043126886 worked on my machine. It would be nice if they ended up in Releases so people can see how easy it is to use :-) 

(Last time I set releases up with Actions it looked like https://github.com/unhammer/bin-your-stars/blob/master/.github/workflows/release.yml but I'm no expert)

**Comment by aavogt** [comment]
The current hackage doesn't build for me:
```
src/Main.hs:73:42: error: [GHC-76037]
    Not in scope: ‘OP.linebreak’
    NB: the module ‘Options.Applicative.Help.Pretty’ does not export ‘linebreak’.
   |
73 |   , O.footerDoc $ Just $ moreInfoText <> OP.linebreak
   |                                          ^^^^^^^^^^^^
```
but this problem is fixed in git

**Comment by lazamar** [comment]
Good idea. I finally got around to it. First release is out.
https://github.com/lazamar/haskell-docs-cli/releases/tag/v1.0.0.0
