### ISSUE TITLE
any plan to add to hackage ?

### ISSUE THREAD

**Issue by teto** [lazamar/haskell-docs-cli#4]
so that nixpkgs can pick it up automatically ?

thanks for writing this cool piece of software.

**Comment by lazamar** [comment]
Yes! It's on my todo list. It's nice to see some demand. I might get around to it tonight.

**Comment by iogrt** [comment]
@teto did you get this working on NixOS? I'm having issues creating the nix script

**Comment by emberdart** [comment]
I'm about to try to include this in my general list of tools to use across projects.

**Comment by emberdart** [comment]
My nix build tools list now contains:
```nix
{
haskell-docs-cli            = (ghc.override {
      overrides = self: super: rec {
        haskell-docs-cli = self.callCabal2nix "haskell-docs-cli" (builtins.fetchGit {
          url = "https://github.com/lazamar/haskell-docs-cli.git";
          rev = "6c40bd41f0f6be5f06afae2836c42710dc05cd87";
        }) {};
      };
    }).haskell-docs-cli;
}
```

& this works great.

**Comment by emberdart** [comment]
It'd still be nice for it to go up to hackage so people won't have to add the override like I have. Are you still interested in maintaining the project, or should someone else do that piece?

**Comment by lazamar** [comment]
I will add it to hackage, I just haven't spared the time to do it yet. 
I'll have a look this weekend.

**Comment by lazamar** [comment]
This is now on hackage https://hackage.haskell.org/package/haskell-docs-cli and running `cabal install haskell-docs-cli` will make the `hdc` binary available.
